service: rynohub-free

frameworkVersion: ">=1.9.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  rootDomain: free.rynoss.com
  devDomains:
    - dev.free.rynoss.com
  prodDomains:
    - free.rynoss.com
provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x
  environment:
    stage: ${opt:stage, self:provider.stage}
    dev_pipedrive_token: 'd64bf10b7e5023c53d380fc9f94e08426420f4db'
    prod_pipedrive_token: '7a97aa50199f46e748ac6359d19f6ee84559a52c'
    dev_slack_hook: 'https://hooks.slack.com/services/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'
    prod_slack_hook: 'https://hooks.slack.com/services/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'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  ${file(resources/functions.yml)}

resources:
  Mappings: ${file(resources/mappings.yml)}
  Outputs: ${file(resources/outputs.yml)}
  Resources:
    WebSite:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          ErrorDocument: 404.html
          IndexDocument: index.html
    SSLCert: ${file(resources/${self:custom.stage}-ssl.yml)}
    CDN:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          ViewerCertificate:
            AcmCertificateArn: {Ref: SSLCert}
            SslSupportMethod: sni-only
          Enabled: true
          HttpVersion: http2
          Aliases: ${self:custom.${self:custom.stage}Domains}
          DefaultRootObject: index.html
          Origins:
            - DomainName: {"Fn::Join": ["", [{Ref: WebSite}, ".", {"Fn::FindInMap": [RegionMap, {Ref: "AWS::Region"}, websiteendpoint]}]]}
              Id: S3Origin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            ViewerProtocolPolicy: allow-all
            TargetOriginId: S3Origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            DefaultTTL: 30
            MinTTL: 10
            ForwardedValues:
              QueryString: true

package:
  exclude:
    - bin/**
    - package.json
    - node_modules/**
  include:
    - node_modules/node-fetch/**
